theme: jekyll-theme-minimal


title: Uncovering Learning Patterns in Collaborative Museum Games
description: Exploring how learners navigate multiplayer game spaces in museums
show_downloads: false
google_analytics: UA-XXXXXXXXX-X


